### PR TITLE
Enable documentation + Add a tutorial for Request injection

### LINKED ISSUE #10: Add documentation on how to use Fluent(Kit)
Currently, I am working on a side project using this Vapor OpenAPI generated package. I am missing documentation on how to use Fluent with the generated code. I would like to use Fluent and I think this is going to be a big use case.

An example of my code:

```swift
import FluentKit
import Foundation
import OpenAPIRuntime
import Vapor

struct UserController: APIProtocol {
    typealias CreationInput = Operations.createUser.Input
    typealias CreationOutput = Operations.createUser.Output

    private let db: any Database

    init(db: any Database) {
        self.db = db
    }

    /// Create a user
    ///
    /// - Remark: HTTP `POST /users`.
    /// - Remark: Generated from `#/paths//users/post(createUser)`.
    func createUser(_ input: CreationInput) async throws -> CreationOutput {
        guard case let CreationInput.Body.json(input) = input.body else { fatalError() }

        let user = try User
            .Signup(name: input.name, email: input.email, password: input.password)
            .createUser()

        try await user.save(on: db)

        let newUser = Components.Schemas.User(
            name: user.name,
            createdAt: user.createdAt ?? .now,
            updatedAt: user.updatedAt ?? .now
        )
        let jsonBody: CreationOutput.Created.Body = .json(newUser)
        let body = CreationOutput.Created(body: jsonBody)

        return .created(body)
    }
}
```

Which results in a warning: `Stored property 'db' of 'Sendable'-conforming struct 'UserController' has non-sendable type 'any Database'`. Therefore, I would like to request documentation on how I am supposed to build out my Vapor app with FluentKit.

### PR DESCRIPTION
**Pull request by MahdiBM**

### CODE REVIEW

**Comment by MahdiBM** [comment]
Just curious:

**Comment by MahdiBM** [comment]
@swift-server-bot test this please

**Comment by 0xTim** [comment]
@swift-server-bot add to allowlist

**Comment by 0xTim** [comment]
@MahdiBM try now

**Comment by MahdiBM** [comment]
@swift-server-bot test this please

**Comment by MahdiBM** [comment]
@0xTim thanks, it's working for this PR at least.

**Review by 0xTim — APPROVED** [review]

**Comment by MahdiBM** [comment]
@0xTim Since you approved, i'll merge this for now to see how it looks like and if it actually works well with the SPI. I'll open up another PR to refine it soon.

**Pull request merged**
