### PR TITLE
Bump runtime dependency to 1.0.0

### PR DESCRIPTION
**Pull request by MahdiBM**

### CODE REVIEW

**Comment by MahdiBM** [comment]
@swift-server-bot test this please

**Comment by MahdiBM** [comment]
@0xTim no CI still, will it respond to you?

**Comment by gwynne** [comment]
@swift-server-bot please test

**Review by 0xTim — APPROVED** [review]

**Comment by 0xTim** [comment]
@swift-server-bot please test this

**Comment by 0xTim** [comment]
@swift-server-bot test this please

**Comment by 0xTim** [comment]
@swift-server-bot test this please

**Pull request merged**
