### PR TITLE
Fix empty path component in route registration

### PR DESCRIPTION
**Pull request by marius-se**
Currently all routes registered through this library will have an empty path component:
Example:
"/users" got split into ["", "users"]. With this PR "/users" will now be split into ["users"] only!

### CODE REVIEW

**Comment by MahdiBM** [comment]
@swift-server-bot test this please

**Review by MahdiBM — APPROVED** [review]
LGTM 👌

**Comment by MahdiBM** [comment]
@0xTim I probably don't have access to ask the bot to run the tests 🤔

**Comment by 0xTim** [comment]
@swift-server-bot test

**Comment by 0xTim** [comment]
@swift-server-bot please test

**Comment by 0xTim** [comment]
@swift-server-bot test this please

**Comment by 0xTim** [comment]
@tomerd how do we trigger CI? 😅

**Comment by marius-se** [comment]
I think @swift-server-bot is oof? 😆

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by 0xTim** [comment]
@marius-se as the error says - do you want to fix the `Equatable` conformance in RoutingKit?

**Comment by MahdiBM** [comment]
I'm not at my desk, but as I see this, you could either not use the equtable conformance or use `#if $Retroactive` to use @retroactive where the feature exists, and not use that when it doesn't like in 5.9. Both are fine by me.

**Comment by MahdiBM** [comment]
Correction: the spelling is `#if $RetroactiveAttribute`.

**Comment by 0xTim** [comment]
We should fix the underlying issue since this is adding the conformance - we shouldn't be extending types we don't own to protocols we don't own. I didn't realise this was a new error but it's definitely a valid one, and one that Vapor is going to get screwed by 😅

**Comment by MahdiBM** [comment]
@0xTim I was also worrying about that when I first reviewed, but @marius-se did it the "fine" way which is to only add it to Tests. That's why I'm fine with it existing. Totally removing it is also fine and might be slightly better as well.

**Comment by marius-se** [comment]
Sooooo... which option do you want me to proceed with 😆
1. Fix in Routing Kit
2. Fix in test (adding retroactively thing)
3. Remove conformance and manually compare

(I'm happy with all three solutions)

**Comment by MahdiBM** [comment]
I think we can proceed with the third option and it should be fine 🙂 
maybe something like:
```swift
let path = try XCTUnwrap(app.routes.all.first?.path)
XCTAssertTrue(path == ["hello", ":name"], "Unexpected path: \(path)")
```
But implementing `==` as a global function, not as a `Equatable` conformance to the type:
```swift
func == (lhs: [PathComponent], rhs: [PathComponent]) -> Bool {
    lhs.count == rhs.count &&
    zip(lhs, rhs).allSatisfy { 
        /// Logic for `$0 == $1`, the same as you wrote for the Equatable conformance
    }
}
```
<Untested code alert, might not compile as-is>

**Comment by MahdiBM** [comment]
Or actually i didn't notice Tim recommending to fix the conformance in RoutingKit

> do you want to fix the Equatable conformance in RoutingKit?

That's fine by me too.
Generally all 3 ways are fine. Fixing the conformance in RoutingKit or using the third way are probably better though.

**Comment by 0xTim** [comment]
You can hack it in for the tests, but I see no issue with adding it directly to RoutingKit as well

**Comment by MahdiBM** [comment]
@marius-se I think this should not be much of a problem now that the RoutingKit PR is merged.

**Comment by MahdiBM** [comment]
@swift-server-bot test this please

**Comment by MahdiBM** [comment]
@0xTim  🫣

**Review by 0xTim — APPROVED** [review]

**Comment by 0xTim** [comment]
@swift-server-bot test this please

**Comment by 0xTim** [comment]
@swift-server-bot please test

**Comment by 0xTim** [comment]
@MahdiBM feel free to merge and release once CI is green

**Review by MahdiBM — APPROVED** [review]

**Pull request merged**
