### PR TITLE
Full compatibility with the "ExistentialAny" upcoming feature

### PR DESCRIPTION
**Pull request by MahdiBM**
Discussed in https://github.com/apple/swift-openapi-generator/pull/99#issuecomment-1630636372

### CODE REVIEW

**Comment by 0xTim** [comment]
@MahdiBM can you update the PR to match https://github.com/apple/swift-openapi-generator/issues/120

**Comment by MahdiBM** [comment]
Is it worth doing anymore, considering this library is quite small?
I'm thinking of just dropping the PR.

**Comment by 0xTim** [comment]
If it's causing warnings in 5.9 we should fix them, but I'm happy for you to close it if it's not worth it

**Comment by MahdiBM** [comment]
I doesn't cause warnings for other libraries.

The reason the generator used to cause _errors_ for other libraries that have the flag enabled, was that the generator inserts its own generated code into other libraries. So the generated code is part of the other libraries from Swift compiler POV, and if it isn't ExistentialAny compatible, there would be an error.

It's a hard decision but considering @czechboy0 didn't even mention these two server-transport libraries (alongside the Hummingbird one) in his request in the first place anyway, i'll just close the PR.
I'll see what i can do with the Hummingbird library considering that's already merged.

**Pull request closed without merging**
